create table ad_account (
  id int auto_increment primary key,
  account_key varchar(64),
  account_name varchar(32),
  api_key varchar(255),
  created timestamp,
  unique key account_key(account_key)
) default character set=utf8mb4 collate utf8mb4_general_ci;

insert into ad_account (account_key, account_name, api_key, created) values
  ('talkingdata', 'TalkingData', '', now());

drop table ad_app;
create table ad_app (
  id int auto_increment primary key,
  app_key varchar(64),
  app_name varchar(32),
  src_timezone varchar(32),
  dst_timezone varchar(32),
  created timestamp,
  unique key account_key(app_key)
) default character set=utf8mb4 collate utf8mb4_general_ci;

insert into ad_app (app_key, app_name, src_timezone, dst_timezone, created) values
  ('battleship2cn', '战舰帝国2-IOS-CN', 'Asia/Shanghai', 'Asia/Shanghai', now());

drop table ad_param_map;
create table ad_param_map (
  id int auto_increment primary key,
  source varchar(24) default null,
  param_name varchar(32),
  std_name varchar(32),
  unique key param_key (source, std_name)
) default character set=utf8mb4 collate utf8mb4_general_ci;

replace into ad_param_map (source, param_name, std_name)
values
  (null, 'stat_id', 'stat_id'),
  (null, 'app_key', 'app_key'),
  (null, 'os_version', 'os_version'),
  (null, 'device_id', 'device_id'),
  (null, 'device_type', 'device_type'),
  (null, 'device_brand', 'device_brand'),
  (null, 'device_carrier', 'device_carrier'),
  (null, 'device_model', 'device_model'),
  (null, 'lang', 'lang'),
  (null, 'plat_id', 'plat_id'),
  (null, 'user_agent', 'user_agent'),
  (null, 'publisher_id', 'publisher_id'),
  (null, 'publisher_name', 'publisher_name'),
  (null, 'click_ip', 'click_ip'),
  (null, 'click_time', 'click_time'),
  (null, 'bundle_id', 'bundle_id'),
  (null, 'ip', 'ip'),
  (null, 'created', 'created'),
  (null, 'agency_name', 'agency_name'),
  (null, 'site_id', 'site_id'),
  (null, 'site_name', 'site_name'),
  (null, 'match_type', 'match_type'),
  (null, 'is_view_through', 'is_view_through'),
  (null, 'is_retarget', 'is_retarget'),
  (null, 'campaign_id', 'campaign_id'),
  (null, 'campaign_name', 'campaign_name'),
  (null, 'ad_url', 'ad_url'),
  (null, 'ad_name', 'ad_name'),
  (null, 'region_name', 'region_name'),
  (null, 'country_code', 'country_code'),
  (null, 'currency_code', 'currency_code'),
  (null, 'existing_user', 'existing_user'),
  (null, 'imp_time', 'imp_time'),
  (null, 'stat_click_id', 'stat_click_id'),
  (null, 'stat_impression_id', 'stat_impression_id'),
  (null, 'payout', 'payout'),
  (null, 'referral_source', 'referral_source'),
  (null, 'referral_url', 'referral_url'),
  (null, 'revenue', 'revenue'),
  (null, 'revenue_usd', 'revenue_usd'),
  (null, 'status', 'status'),
  (null, 'status_code', 'status_code'),
  (null, 'tracking_id', 'tracking_id'),
  (null, 'ios_ifa', 'ios_ifa'),
  (null, 'ios_ifv', 'ios_ifv'),
  (null, 'google_aid', 'google_aid'),
  (null, 'pub_camp_id', 'pub_camp_id'),
  (null, 'pub_camp_name', 'pub_camp_name'),
  (null, 'pub_camp_ref', 'pub_camp_ref'),
  (null, 'pub_adset', 'pub_adset'),
  (null, 'pub_ad', 'pub_ad'),
  (null, 'pub_keyword', 'pub_keyword'),
  (null, 'pub_place', 'pub_place'),
  (null, 'pub_sub_id', 'pub_sub_id'),
  (null, 'pub_sub_name', 'pub_sub_name'),
  (null, 'adv_camp_id', 'adv_camp_id'),
  (null, 'adv_camp_name', 'adv_camp_name'),
  (null, 'adv_camp_ref', 'adv_camp_ref'),
  (null, 'adv_adset', 'adv_adset'),
  (null, 'adv_ad', 'adv_ad'),
  (null, 'adv_keyword', 'adv_keyword'),
  (null, 'adv_place', 'adv_place'),
  (null, 'adv_sub_id', 'adv_sub_id'),
  (null, 'adv_sub_name', 'adv_sub_name'),
  (null, 'sdk', 'sdk'),
  (null, 'sdk_version', 'sdk_version'),
  (null, 'game_user_id', 'game_user_id'),
  (null, 'os_jailbroke', 'os_jailbroke'),
  (null, 'pub_ref_id', 'pub_pref_id'),
  (null, 'pub_sub1', 'pub_sub1'),
  (null, 'pub_sub2', 'pub_sub2'),
  (null, 'pub_sub3', 'pub_sub3'),
  (null, 'cost_model', 'cost_model'),
  (null, 'cost', 'cost'),
  (null, 'ip_from', 'ip_from'),
  (null, 'ip_to', 'ip_to'),
  (null, 'city_code', 'city_code'),
  (null, 'metro_code', 'metro_code'),
  ('test', 'created', 'install_time');


drop table ad_install;
create table ad_install (
  action varchar(50) DEFAULT 'install',
  account_key varchar(50) DEFAULT NULL,
  ip varchar(50) DEFAULT NULL,
  created datetime,
  source varchar(50) DEFAULT NULL,
  stat_id varchar(100) DEFAULT NULL,
  app_key varchar(100) DEFAULT NULL,
  os_version varchar(20) DEFAULT NULL,
  device_id varchar(100) DEFAULT NULL,
  device_type varchar(50) DEFAULT NULL,
  device_brand  varchar(50) DEFAULT NULL,
  device_carrier  varchar(50) DEFAULT NULL,
  device_model  varchar(50) DEFAULT NULL,
  lang  varchar(10) DEFAULT NULL,
  plat_id varchar(100) DEFAULT NULL,
  user_agent varchar(200) DEFAULT NULL,
  publisher_id varchar(50) DEFAULT NULL,
  publisher_name varchar(50) DEFAULT NULL,
  click_ip varchar(50) DEFAULT NULL,
  click_time datetime,
  bundle_id varchar(100) DEFAULT NULL,
  agency_name varchar(50) DEFAULT NULL,
  site_id varchar(50) DEFAULT NULL,
  site_name varchar(100) DEFAULT NULL,
  match_type varchar(50) DEFAULT NULL,
  campaign_id varchar(50) DEFAULT NULL,
  campaign_name varchar(100) DEFAULT NULL,
  ad_url varchar(200) DEFAULT NULL,
  ad_name varchar(50) DEFAULT NULL,
  region_name varchar(50) DEFAULT NULL,
  country_code varchar(20) DEFAULT NULL,
  currency_code varchar(10) DEFAULT NULL,
  existing_user boolean,
  imp_time datetime,
  stat_click_id varchar(100) DEFAULT NULL,
  stat_impression_id varchar(100) DEFAULT NULL,
  payout double,
  referral_source varchar(200) DEFAULT NULL,
  referral_url varchar(200) DEFAULT NULL,
  revenue double,
  revenue_usd double,
  status varchar(50) DEFAULT NULL,
  status_code varchar(20) DEFAULT NULL,
  tracking_id varchar(100) DEFAULT NULL,
  ios_ifa varchar(100) DEFAULT NULL,
  ios_ifv varchar(100) DEFAULT NULL,
  google_aid varchar(100) DEFAULT NULL,
  pub_camp_id varchar(50) DEFAULT NULL,
  pub_camp_name varchar(50) DEFAULT NULL,
  pub_camp_ref varchar(50) DEFAULT NULL,
  pub_adset varchar(50) DEFAULT NULL,
  pub_ad varchar(50) DEFAULT NULL,
  pub_keyword varchar(50) DEFAULT NULL,
  pub_place varchar(50) DEFAULT NULL,
  pub_sub_id varchar(50) DEFAULT NULL,
  pub_sub_name varchar(50) DEFAULT NULL,
  adv_camp_id varchar(50) DEFAULT NULL,
  adv_camp_name varchar(50) DEFAULT NULL,
  adv_camp_ref varchar(50) DEFAULT NULL,
  adv_adset varchar(50) DEFAULT NULL,
  adv_ad varchar(50) DEFAULT NULL,
  adv_keyword varchar(50) DEFAULT NULL,
  adv_place varchar(50) DEFAULT NULL,
  adv_sub_id varchar(50) DEFAULT NULL,
  adv_sub_name varchar(50) DEFAULT NULL,
  sdk varchar(20) DEFAULT NULL,
  sdk_version varchar(20) DEFAULT NULL,
  game_user_id varchar(100) DEFAULT NULL,
  os_jailbroke boolean,
  pub_pref_id varchar(50) DEFAULT NULL,
  pub_sub1 varchar(50) DEFAULT NULL,
  pub_sub2 varchar(50) DEFAULT NULL,
  pub_sub3 varchar(50) DEFAULT NULL,
  pub_sub4 varchar(50) DEFAULT NULL,
  pub_sub5 varchar(50) DEFAULT NULL,
  cost_model varchar(50) DEFAULT NULL,
  cost double,
  ip_from int(11),
  ip_to  int(11),
  city_code varchar(20) DEFAULT NULL,
  metro_code varchar(20) DEFAULT NULL,
  unique key id (action, source, stat_id, created, app_key),
  key install_time (created),
  key aid ( ios_ifa, google_aid )
) default character set=utf8mb4 collate utf8mb4_general_ci;

drop table ad_purchase;
create table ad_purchase(
  action varchar(50) DEFAULT 'install',
  account_key varchar(50) DEFAULT NULL,
  ip varchar(50) DEFAULT NULL,
  created datetime,
  source varchar(50) DEFAULT NULL,
  stat_id varchar(100) DEFAULT NULL,
  app_key varchar(100) DEFAULT NULL,
  os_version varchar(20) DEFAULT NULL,
  device_id varchar(100) DEFAULT NULL,
  device_type varchar(50) DEFAULT NULL,
  device_brand  varchar(50) DEFAULT NULL,
  device_carrier  varchar(50) DEFAULT NULL,
  device_model  varchar(50) DEFAULT NULL,
  lang  varchar(10) DEFAULT NULL,
  plat_id varchar(100) DEFAULT NULL,
  user_agent varchar(200) DEFAULT NULL,
  publisher_id varchar(50) DEFAULT NULL,
  publisher_name varchar(50) DEFAULT NULL,
  click_ip varchar(50) DEFAULT NULL,
  click_time datetime,
  bundle_id varchar(100) DEFAULT NULL,
  agency_name varchar(50) DEFAULT NULL,
  site_id varchar(50) DEFAULT NULL,
  site_name varchar(100) DEFAULT NULL,
  match_type varchar(50) DEFAULT NULL,
  campaign_id varchar(50) DEFAULT NULL,
  campaign_name varchar(100) DEFAULT NULL,
  ad_url varchar(200) DEFAULT NULL,
  ad_name varchar(50) DEFAULT NULL,
  region_name varchar(50) DEFAULT NULL,
  country_code varchar(20) DEFAULT NULL,
  currency_code varchar(10) DEFAULT NULL,
  existing_user boolean,
  imp_time datetime,
  stat_click_id varchar(100) DEFAULT NULL,
  stat_impression_id varchar(100) DEFAULT NULL,
  payout double,
  referral_source varchar(200) DEFAULT NULL,
  referral_url varchar(200) DEFAULT NULL,
  revenue double,
  revenue_usd double,
  status varchar(50) DEFAULT NULL,
  status_code varchar(20) DEFAULT NULL,
  tracking_id varchar(100) DEFAULT NULL,
  ios_ifa varchar(100) DEFAULT NULL,
  ios_ifv varchar(100) DEFAULT NULL,
  google_aid varchar(100) DEFAULT NULL,
  pub_camp_id varchar(50) DEFAULT NULL,
  pub_camp_name varchar(50) DEFAULT NULL,
  pub_camp_ref varchar(50) DEFAULT NULL,
  pub_adset varchar(50) DEFAULT NULL,
  pub_ad varchar(50) DEFAULT NULL,
  pub_keyword varchar(50) DEFAULT NULL,
  pub_place varchar(50) DEFAULT NULL,
  pub_sub_id varchar(50) DEFAULT NULL,
  pub_sub_name varchar(50) DEFAULT NULL,
  adv_camp_id varchar(50) DEFAULT NULL,
  adv_camp_name varchar(50) DEFAULT NULL,
  adv_camp_ref varchar(50) DEFAULT NULL,
  adv_adset varchar(50) DEFAULT NULL,
  adv_ad varchar(50) DEFAULT NULL,
  adv_keyword varchar(50) DEFAULT NULL,
  adv_place varchar(50) DEFAULT NULL,
  adv_sub_id varchar(50) DEFAULT NULL,
  adv_sub_name varchar(50) DEFAULT NULL,
  sdk varchar(20) DEFAULT NULL,
  sdk_version varchar(20) DEFAULT NULL,
  game_user_id varchar(100) DEFAULT NULL,
  os_jailbroke boolean,
  pub_pref_id varchar(50) DEFAULT NULL,
  pub_sub1 varchar(50) DEFAULT NULL,
  pub_sub2 varchar(50) DEFAULT NULL,
  pub_sub3 varchar(50) DEFAULT NULL,
  pub_sub4 varchar(50) DEFAULT NULL,
  pub_sub5 varchar(50) DEFAULT NULL,
  cost_model varchar(50) DEFAULT NULL,
  cost double,
  ip_from int(11),
  ip_to  int(11),
  city_code varchar(20) DEFAULT NULL,
  metro_code varchar(20) DEFAULT NULL,
  unique key id (action, source, stat_id, created, app_key),
  key install_time (created),
  key aid ( ios_ifa, google_aid )
) default character set=utf8mb4 collate utf8mb4_general_ci;

drop table ad_click;
create table ad_click (
  action varchar(50) DEFAULT 'install',
  account_key varchar(50) DEFAULT NULL,
  ip varchar(50) DEFAULT NULL,
  created datetime,
  source varchar(50) DEFAULT NULL,
  stat_id varchar(100) DEFAULT NULL,
  app_key varchar(100) DEFAULT NULL,
  os_version varchar(20) DEFAULT NULL,
  device_id varchar(100) DEFAULT NULL,
  device_type varchar(50) DEFAULT NULL,
  device_brand  varchar(50) DEFAULT NULL,
  device_carrier  varchar(50) DEFAULT NULL,
  device_model  varchar(50) DEFAULT NULL,
  lang  varchar(10) DEFAULT NULL,
  plat_id varchar(100) DEFAULT NULL,
  user_agent varchar(200) DEFAULT NULL,
  publisher_id varchar(50) DEFAULT NULL,
  publisher_name varchar(50) DEFAULT NULL,
  click_ip varchar(50) DEFAULT NULL,
  click_time datetime,
  bundle_id varchar(100) DEFAULT NULL,
  agency_name varchar(50) DEFAULT NULL,
  site_id varchar(50) DEFAULT NULL,
  site_name varchar(100) DEFAULT NULL,
  match_type varchar(50) DEFAULT NULL,
  campaign_id varchar(50) DEFAULT NULL,
  campaign_name varchar(100) DEFAULT NULL,
  ad_url varchar(200) DEFAULT NULL,
  ad_name varchar(50) DEFAULT NULL,
  region_name varchar(50) DEFAULT NULL,
  country_code varchar(20) DEFAULT NULL,
  currency_code varchar(10) DEFAULT NULL,
  existing_user boolean,
  imp_time datetime,
  stat_click_id varchar(100) DEFAULT NULL,
  stat_impression_id varchar(100) DEFAULT NULL,
  payout double,
  referral_source varchar(200) DEFAULT NULL,
  referral_url varchar(200) DEFAULT NULL,
  revenue double,
  revenue_usd double,
  status varchar(50) DEFAULT NULL,
  status_code varchar(20) DEFAULT NULL,
  tracking_id varchar(100) DEFAULT NULL,
  ios_ifa varchar(100) DEFAULT NULL,
  ios_ifv varchar(100) DEFAULT NULL,
  google_aid varchar(100) DEFAULT NULL,
  pub_camp_id varchar(50) DEFAULT NULL,
  pub_camp_name varchar(50) DEFAULT NULL,
  pub_camp_ref varchar(50) DEFAULT NULL,
  pub_adset varchar(50) DEFAULT NULL,
  pub_ad varchar(50) DEFAULT NULL,
  pub_keyword varchar(50) DEFAULT NULL,
  pub_place varchar(50) DEFAULT NULL,
  pub_sub_id varchar(50) DEFAULT NULL,
  pub_sub_name varchar(50) DEFAULT NULL,
  adv_camp_id varchar(50) DEFAULT NULL,
  adv_camp_name varchar(50) DEFAULT NULL,
  adv_camp_ref varchar(50) DEFAULT NULL,
  adv_adset varchar(50) DEFAULT NULL,
  adv_ad varchar(50) DEFAULT NULL,
  adv_keyword varchar(50) DEFAULT NULL,
  adv_place varchar(50) DEFAULT NULL,
  adv_sub_id varchar(50) DEFAULT NULL,
  adv_sub_name varchar(50) DEFAULT NULL,
  sdk varchar(20) DEFAULT NULL,
  sdk_version varchar(20) DEFAULT NULL,
  game_user_id varchar(100) DEFAULT NULL,
  os_jailbroke boolean,
  pub_pref_id varchar(50) DEFAULT NULL,
  pub_sub1 varchar(50) DEFAULT NULL,
  pub_sub2 varchar(50) DEFAULT NULL,
  pub_sub3 varchar(50) DEFAULT NULL,
  pub_sub4 varchar(50) DEFAULT NULL,
  pub_sub5 varchar(50) DEFAULT NULL,
  cost_model varchar(50) DEFAULT NULL,
  cost double,
  ip_from int(11),
  ip_to  int(11),
  city_code varchar(20) DEFAULT NULL,
  metro_code varchar(20) DEFAULT NULL,
  unique key id (action, source, stat_id, created, app_key),
  key install_time (created),
  key aid ( ios_ifa, google_aid )
) default character set=utf8mb4 collate utf8mb4_general_ci;

drop table ad_event;
create table ad_event (
  action varchar(50) DEFAULT 'install',
  account_key varchar(50) DEFAULT NULL,
  ip varchar(50) DEFAULT NULL,
  created datetime,
  source varchar(50) DEFAULT NULL,
  stat_id varchar(100) DEFAULT NULL,
  app_key varchar(100) DEFAULT NULL,
  os_version varchar(20) DEFAULT NULL,
  device_id varchar(100) DEFAULT NULL,
  device_type varchar(50) DEFAULT NULL,
  device_brand  varchar(50) DEFAULT NULL,
  device_carrier  varchar(50) DEFAULT NULL,
  device_model  varchar(50) DEFAULT NULL,
  lang  varchar(10) DEFAULT NULL,
  plat_id varchar(100) DEFAULT NULL,
  user_agent varchar(200) DEFAULT NULL,
  publisher_id varchar(50) DEFAULT NULL,
  publisher_name varchar(50) DEFAULT NULL,
  click_ip varchar(50) DEFAULT NULL,
  click_time datetime,
  bundle_id varchar(100) DEFAULT NULL,
  agency_name varchar(50) DEFAULT NULL,
  site_id varchar(50) DEFAULT NULL,
  site_name varchar(100) DEFAULT NULL,
  match_type varchar(50) DEFAULT NULL,
  campaign_id varchar(50) DEFAULT NULL,
  campaign_name varchar(100) DEFAULT NULL,
  ad_url varchar(200) DEFAULT NULL,
  ad_name varchar(50) DEFAULT NULL,
  region_name varchar(50) DEFAULT NULL,
  country_code varchar(20) DEFAULT NULL,
  currency_code varchar(10) DEFAULT NULL,
  existing_user boolean,
  imp_time datetime,
  stat_click_id varchar(100) DEFAULT NULL,
  stat_impression_id varchar(100) DEFAULT NULL,
  payout double,
  referral_source varchar(200) DEFAULT NULL,
  referral_url varchar(200) DEFAULT NULL,
  revenue double,
  revenue_usd double,
  status varchar(50) DEFAULT NULL,
  status_code varchar(20) DEFAULT NULL,
  tracking_id varchar(100) DEFAULT NULL,
  ios_ifa varchar(100) DEFAULT NULL,
  ios_ifv varchar(100) DEFAULT NULL,
  google_aid varchar(100) DEFAULT NULL,
  pub_camp_id varchar(50) DEFAULT NULL,
  pub_camp_name varchar(50) DEFAULT NULL,
  pub_camp_ref varchar(50) DEFAULT NULL,
  pub_adset varchar(50) DEFAULT NULL,
  pub_ad varchar(50) DEFAULT NULL,
  pub_keyword varchar(50) DEFAULT NULL,
  pub_place varchar(50) DEFAULT NULL,
  pub_sub_id varchar(50) DEFAULT NULL,
  pub_sub_name varchar(50) DEFAULT NULL,
  adv_camp_id varchar(50) DEFAULT NULL,
  adv_camp_name varchar(50) DEFAULT NULL,
  adv_camp_ref varchar(50) DEFAULT NULL,
  adv_adset varchar(50) DEFAULT NULL,
  adv_ad varchar(50) DEFAULT NULL,
  adv_keyword varchar(50) DEFAULT NULL,
  adv_place varchar(50) DEFAULT NULL,
  adv_sub_id varchar(50) DEFAULT NULL,
  adv_sub_name varchar(50) DEFAULT NULL,
  sdk varchar(20) DEFAULT NULL,
  sdk_version varchar(20) DEFAULT NULL,
  game_user_id varchar(100) DEFAULT NULL,
  os_jailbroke boolean,
  pub_pref_id varchar(50) DEFAULT NULL,
  pub_sub1 varchar(50) DEFAULT NULL,
  pub_sub2 varchar(50) DEFAULT NULL,
  pub_sub3 varchar(50) DEFAULT NULL,
  pub_sub4 varchar(50) DEFAULT NULL,
  pub_sub5 varchar(50) DEFAULT NULL,
  cost_model varchar(50) DEFAULT NULL,
  cost double,
  ip_from int(11),
  ip_to  int(11),
  city_code varchar(20) DEFAULT NULL,
  metro_code varchar(20) DEFAULT NULL,
  unique key id (action, source, stat_id, created, app_key),
  key install_time (created),
  key aid ( ios_ifa, google_aid )
) default character set=utf8mb4 collate utf8mb4_general_ci;


drop table ad_currency;
create table ad_currency (
  id int(11) primary key auto_increment,
  created date,
  currency_code char(3),
  rate double,
  unique key idx (created, currency_code)
) default character set=utf8mb4 collate utf8mb4_general_ci;

